name: utonia

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - cuda
  - cudnn
  - gcc=8.5      # older gcc compatible with py37
  - gxx=8.5
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7   # or 11.6 / 11.3 depending on your GPU
  - numpy=1.21.6
  - ninja
  - scipy
  - addict
  - timm
  - psutil
  - huggingface_hub
  - open3d
  - matplotlib
  - pip:
    - torch-scatter -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - git+https://github.com/Dao-AILab/flash-attention.git@v1.0.9   # older stable version
    - spconv-cu117
    - opencv-python
    - camtools
    - trimesh
    - natsort
    - gradio==3.50.2     # newer gradio may not support py37
    - einops
